version: "3"
services:
    mongo1:
        image: "mongo"
        ports:
            - "27017:27017"
        volumes: 
            - $HOME/mongoRepl/mongo1:/data/db
        networks:
            - mongo-networks
        command: mongod --replSet myapp
            
    mongo2:
        image: "mongo"
        ports:
            - "27018:27017"
        volumes: 
            - $HOME/mongoRepl/mongo2:/data/db
        networks:
            - mongo-networks
        command: mongod --replSet myapp
        depends_on: 
            - mongo1

    mongo3:
        image: "mongo"
        ports:
            - "27019:27017"
        volumes: 
            - $HOME/mongoRepl/mongo3:/data/db
        networks:
            - mongo-networks
        command: mongod --replSet myapp 
        depends_on: 
            - mongo2
            
    mongodb_setup:
        image: "mongo_repl_setup"
        depends_on: 
            - mongo3
        networks:
            - mongo-networks
        
networks: 
    mongo-networks:
        driver: bridge        